require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

<% module_namespacing do -%>
describe <%= controller_class_name %>Controller do

  # stub cancan's current_ability.
  # Any ability logic should be tested against the Ability class.
  let(:ability) { Object.new.tap {|o| o.extend CanCan::Ability } }
  before(:each) do
    ability.can [:create, :read, :update, :destroy], :<%= table_name.pluralize %>
    controller.stub(current_ability: ability)
  end

  # This should return the minimal set of attributes required to create a valid
  # <%= class_name %>. As you add validations to <%= class_name %>, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # <%= controller_class_name %>Controller. Be sure to keep this updated too.
  def valid_session
    {}
  end

  # Additional params sent with each request
  # Convenient for nested controllers.
  def default_params
    {}
  end

<% unless options[:singleton] -%>
  describe "GET index" do
    it "assigns all <%= table_name.pluralize %> as @<%= table_name.pluralize %>" do
      <%= file_name %> = <%= class_name %>.create! valid_attributes
      get :index, params: , valid_session
      assigns(:<%= table_name %>).should eq([<%= file_name %>])
    end
  end

<% end -%>
  describe "GET show" do
    it "assigns the requested <%= ns_file_name %> as @<%= ns_file_name %>" do
      <%= file_name %> = <%= class_name %>.create! valid_attributes
      get :show, params: default_params.merge(id: <%= file_name %>.to_param), valid_session
      assigns(:<%= ns_file_name %>).should eq(<%= file_name %>)
    end
  end

  describe "GET new" do
    it "assigns a new <%= ns_file_name %> as @<%= ns_file_name %>" do
      get :new, params: , valid_session
      assigns(:<%= ns_file_name %>).should be_a_new(<%= class_name %>)
    end
  end

  describe "GET edit" do
    it "assigns the requested <%= ns_file_name %> as @<%= ns_file_name %>" do
      <%= file_name %> = <%= class_name %>.create! valid_attributes
      get :edit, params: default_params.merge(id: <%= file_name %>.to_param), valid_session
      assigns(:<%= ns_file_name %>).should eq(<%= file_name %>)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new <%= class_name %>" do
        expect {
          post :create, params: default_params.merge(<%= ns_file_name %>: valid_attributes), valid_session
        }.to change(<%= class_name %>, :count).by(1)
      end

      it "assigns a newly created <%= ns_file_name %> as @<%= ns_file_name %>" do
        post :create, params: default_params.merge(<%= ns_file_name %>: valid_attributes), valid_session
        assigns(:<%= ns_file_name %>).should be_a(<%= class_name %>)
        assigns(:<%= ns_file_name %>).should be_persisted
      end

      it "redirects to the created <%= ns_file_name %>" do
        post :create, params: default_params.merge(<%= ns_file_name %>: valid_attributes), valid_session
        response.should redirect_to(<%= class_name %>.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved <%= ns_file_name %> as @<%= ns_file_name %>" do
        # Trigger the behavior that occurs when invalid params are submitted
        <%= class_name %>.any_instance.stub(:save).and_return(false)
        <%= class_name %>.any_instance.stub(:errors).and_return(double(:errors, empty?: false))
        post :create, params: default_params.merge(<%= ns_file_name %>: {}), valid_session
        assigns(:<%= ns_file_name %>).should be_a_new(<%= class_name %>)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        <%= class_name %>.any_instance.stub(:save).and_return(false)
        <%= class_name %>.any_instance.stub(:errors).and_return(double(:errors, empty?: false))
        post :create, params: default_params.merge(<%= ns_file_name %>: {}), valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested <%= ns_file_name %>" do
        <%= file_name %> = <%= class_name %>.create! valid_attributes
        # Assuming there are no other <%= table_name %> in the database, this
        # specifies that the <%= class_name %> created on the previous line
        # receives the :attributes= message with whatever params are submitted
        # in the request, and then :save.
        <%= class_name %>.any_instance.should_receive(:attributes=).with(<%= formatted_hash(example_params_for_update) %>)
        <%= class_name %>.any_instance.should_receive(:save).and_return(false)
        put :update, params: default_params.merge(id: <%= file_name %>.to_param, <%= ns_file_name %>: <%= formatted_hash(example_params_for_update) %>), valid_session
      end

      it "assigns the requested <%= ns_file_name %> as @<%= ns_file_name %>" do
        <%= file_name %> = <%= class_name %>.create! valid_attributes
        put :update, params: default_params.merge(id: <%= file_name %>.to_param, <%= ns_file_name %>: valid_attributes), valid_session
        assigns(:<%= ns_file_name %>).should eq(<%= file_name %>)
      end

      it "redirects to the <%= ns_file_name %>" do
        <%= file_name %> = <%= class_name %>.create! valid_attributes
        put :update, params: default_params.merge(id: <%= file_name %>.to_param, <%= ns_file_name %>: valid_attributes), valid_session
        response.should redirect_to(<%= file_name %>)
      end
    end

    describe "with invalid params" do
      it "assigns the <%= ns_file_name %> as @<%= ns_file_name %>" do
        <%= file_name %> = <%= class_name %>.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        <%= class_name %>.any_instance.stub(:save).and_return(false)
        <%= class_name %>.any_instance.stub(:errors).and_return(double(:errors, empty?: false))
        put :update, params: default_params.merge(id: <%= file_name %>.to_param, <%= ns_file_name %>: <%= formatted_hash(example_invalid_attributes) %>), valid_session
        assigns(:<%= ns_file_name %>).should eq(<%= file_name %>)
      end

      it "re-renders the 'edit' template" do
        <%= file_name %> = <%= class_name %>.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        <%= class_name %>.any_instance.stub(:save).and_return(false)
        <%= class_name %>.any_instance.stub(:errors).and_return(double(:errors, empty?: false))
        put :update, params: default_params.merge(id: <%= file_name %>.to_param, <%= ns_file_name %>: <%= formatted_hash(example_invalid_attributes) %>), valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested <%= ns_file_name %>" do
      <%= file_name %> = <%= class_name %>.create! valid_attributes
      expect {
        delete :destroy, params: default_params.merge(id: <%= file_name %>.to_param), valid_session
      }.to change(<%= class_name %>, :count).by(-1)
    end

    it "redirects to the <%= table_name %> list" do
      <%= file_name %> = <%= class_name %>.create! valid_attributes
      delete :destroy, params: default_params.merge(id: <%= file_name %>.to_param), valid_session
      response.should redirect_to(<%= index_helper %>_url)
    end
  end

end
<% end -%>
